// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using awsomAPI.Models;

namespace awsomAPI.Migrations
{
    [DbContext(typeof(AwsomApiContext))]
    partial class AwsomApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("awsomAPI.Models.TrialRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Availability");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Experience");

                    b.Property<bool>("HasInstrument");

                    b.Property<List<string>>("Instrument")
                        .IsRequired();

                    b.Property<string>("Notes");

                    b.Property<string>("ParentName")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("StudentBirthDate");

                    b.Property<string>("StudentName")
                        .IsRequired();

                    b.Property<List<string>>("TeachersSelected");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("TrialRequests");
                });

            modelBuilder.Entity("awsomAPI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<List<string>>("InstrumentsTaught");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<int>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
